### PR TITLE
Update License text in README

### PR DESCRIPTION
**Pull request by loafyloaf**

### CODE REVIEW

**Review by dolph — APPROVED** [review]
LGTM, pending a corresponding change to the [readme template](https://github.ibm.com/IBMCode/IBMCodeContent/blob/master/docs/patterns/templates/readme-template.md).

**Comment by ljbennett62** [comment]
@dolph - will you make the change to the template - I don't seem to have the authority to update

**Review by markstur — CHANGES_REQUESTED** [review]
This one left "Developer" our of the DCO link brackets.
Also we need to decide if we are ending our patterns w/ that "I'm not a lawyer thing". There are other versions floating around.
Need an approved template first so we can get these right. Sounds easy, right?

**Comment by markstur** [comment]
there's a new pr consistent with the others

**Pull request closed without merging**
